name: Build Android
on: [push]
jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12

    - name: Install Deps & Ionic
      run: |
        cd frontend
        npm install -g ionic
        ionic --no-interactive config set -g daemon.updates false
        npm install

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Version information
      run: |
        cd frontend
        node --version
        npm --version
        ionic --version
        npm run ng v
        java -version

    - name: Build Android app
      run: |
        cd frontend/android
        chmod +x gradlew
        ./gradlew

    - name: Upload Android app
      uses: actions/upload-artifact@v1
      with:
        name: android-app
        path: frontend/android/app/build/outputs/apk/debug
