name: Build iOS
on: [push]
jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 12

    - name: Install Deps & Ionic
      run: |
        cd frontend
        npm install -g ionic
        ionic --no-interactive config set -g daemon.updates false
        npm install

    - name: Setup XCode
      uses: sinoru/actions-setup-xcode@v1.1
      with:
        xcode-version: '11.2.1'

    - name: Version information
      run: |
        cd frontend
        node --version
        npm --version
        ionic --version
        npm run ng v
        xcodebuild -version

    - name: Build Ionic app and prepare iOS App
      run: |
        cd frontend
        ionic build
        npx cap sync

    - name: Build iOS app
      run: |
        cd frontend/ios/App
        pod install
        xcodebuild -workspace App.xcworkspace \
          -scheme App \ 
          -sdk iphoneos \ 
          -configuration Release archive -archivePath $PWD/build/App.xcarchive
        xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive \ 
          -exportOptionsPlist build/App.xcarchive/info.plist \ 
          -exportPath $PWD/build/Covidiary.ipa

    - name: Upload iOS app
      uses: actions/upload-artifact@v1
      with:
        name: ios-app
        path: frontend/ios/build/Covidiary.app
